# Generated by Django 5.0.1 on 2024-02-22 06:59

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.getFileName)),
                ('description', models.TextField(max_length=500)),
                ('avelable', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('id_number', models.TextField(max_length=255)),
                ('qulification', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('doc_image', models.ImageField(blank=True, null=True, upload_to=home.models.getFileName)),
                ('special', models.TextField(max_length=500)),
                ('languages', models.TextField(max_length=100)),
                ('experience', models.IntegerField()),
                ('fees', models.FloatField()),
                ('avel_dates', models.TextField(max_length=100)),
                ('in_out_time', models.TextField(max_length=50)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('doc_avelable', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('address', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catagory')),
            ],
        ),
    ]
