# Generated by Django 5.0.1 on 2024-02-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fh',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
