# Generated by Django 5.0.1 on 2024-02-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_fh'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fh', models.CharField(max_length=100)),
                ('nadate', models.DateField()),
                ('prc', models.CharField(max_length=1000)),
            ],
        ),
    ]
