# Generated by Django 5.0.1 on 2024-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='description',
            field=models.TextField(default=0),
        ),
    ]
