# Generated by Django 5.0.1 on 2024-02-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_prescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='nadate',
            field=models.DateField(default=0),
        ),
    ]
