# Generated by Django 5.0.1 on 2024-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_prescription_doctor_alter_prescription_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='nadate',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
